### PR TITLE
Rename subprocess to process

### PR DESCRIPTION
**Pull request by andreabolognani**
@elmarco It's a straightforward search and replace, and CI will confirm it works. Just wanted to make sure you're okay with it since you came up with the name in the first place...

### CODE REVIEW

**Comment by elmarco** [comment]
I really prefer "subprocess". "process" would refer to current process.

Anyway, this is just a toy, and I don't think anything should use that code directly honestly. so feel free.

**Comment by andreabolognani** [comment]
> I really prefer "subprocess". "process" would refer to current process.

Fair point. How about "command"? That's actually more accurate than either of the alternatives.

**Comment by nertpinx** [comment]
On Wed, Sep 11, 2019 at 08:29:04AM -0700, Andrea Bolognani wrote:
>> I really prefer "subprocess". "process" would refer to current process.
>
>Fair point. How about "command"? That's actually more accurate than either of the alternatives.
>

+1 for "command" even though both exist in the standard library (see std::process::Command)

**Comment by andreabolognani** [comment]
> +1 for "command" even though both exist in the standard library (see std::process::Command)

Indeed, our own implementation uses `std::process::Command` behind the scenes ;)

**Comment by andreabolognani** [comment]
Merging since @elmarco was not strongly against renaming the object and @nertpinx supported the idea.

**Pull request merged**
