### PR TITLE
license: Adopt LGPL-2.1-or-later

### PR DESCRIPTION
**Pull request by andreabolognani**
Same as #11.

All contributors (@rmohr, @nertpinx, @janotomko, @elmarco), please comment on this PR with your `Signed-off-by` tag to agree to the license change.

### CODE REVIEW

**Comment by janotomko** [comment]
Signed-off-by: Ján Tomko &lt;jtomko@redhat.com&gt;

**Comment by elmarco** [comment]
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>

**Comment by rmohr** [comment]
Signed-off-by: Roman Mohr <rmohr@redhat.com>

**Comment by nertpinx** [comment]
I don't really see the point in differentiating LGPL-2.1+ for the Virt Blocks code without future dependencies (which will probably not be usable) and LGPL-3.0+ for the combined work, which it will most likely be used as (and in the long run I don't see how it would be usable without some dependencies), but since I'm fine with both LGPL-2.1+ and LGPL-3.0+, then consider this:

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>

I also don't see how usable is this going to be for KubeVirt unless we're going with separate daemon, but since @rmohr signed off already, I'm guessing it's fine for them.

**Comment by andreabolognani** [comment]
> I also don't see how usable is this going to be for KubeVirt unless we're going with separate daemon, but since @rmohr signed off already, I'm guessing it's fine for them.

Yeah, the part of KubeVirt that needs to talk to QEMU (`virt-launcher`) Is already a separate binary and they're okay with using (L)GPL for it.

**Comment by rmohr** [comment]
> Yeah, the part of KubeVirt that needs to talk to QEMU (`virt-launcher`) Is already a separate binary and they're okay with using (L)GPL for it.

Not virt-launcher will do that, but yes the idea is right, we just wrap it in a compatible way.

**Comment by andreabolognani** [comment]
> Not virt-launcher will do that, but yes the idea is right, we just wrap it in a compatible way.

Oh, it looks like I partially misunderstood! Thanks for clearing that up :)

Anyway, we have all `Signed-off-by`s now, so I'm going to go ahead and merge. @nertpinx raises a good point with regards to LGPL-2.1-or-later vs LGPL-3.0-or-later, but we can consider that separately and just switch licenses again if the latter turns out to be a better choice.

Thanks everyone!

**Comment by andreabolognani** [comment]
Merged as ffe26a8a4cc569259dd71676e86854d7776ce4e0.

**Pull request closed without merging**
