### PR TITLE
QEMU command line fixes

### PR DESCRIPTION
**Pull request by andreabolognani**
Obvious fixes to our QEMU command line generator. I'll merge as soon as CI passes.

### CODE REVIEW

**Comment by andreabolognani** [comment]
@rmohr any idea what's going on here? The changes are the definition of trivial, checks pass locally, and there seems to be no log on the prow side for the failed jobs.

**Comment by rmohr** [comment]
They probably got canceled at the Pod level (Maybe maintenance or a node is in trouble).

/retest

Runs all failed lanes again.

**Comment by rmohr** [comment]
Will look into the logs when I am on the computer. Can't right now.

**Comment by andreabolognani** [comment]
2/3 passed the second time around, so let's try another

/retest

and see if that gets rid of the last failure as well.

**Comment by andreabolognani** [comment]
Yup, that did the trick :)

**Pull request merged**
