### PR TITLE
Drop Rust implementation

### PR DESCRIPTION
**Pull request by andreabolognani**
Plus a couple of fixes that are apparently necessary to keep the C bindings building successfully now that we have split the private headers.

@rmohr as agreed I'll merge this once CI has passed, after which feel free to take a look at the Go code and point out any issues you might find :)

### CODE REVIEW

**Comment by andreabolognani** [comment]
@rmohr note there's quite a bit of Go code in the C bindings as well, and that too could use some vetting from an experienced Go coder...

**Comment by rmohr** [comment]
@andreabolognani on it. :+1:

**Comment by rmohr** [comment]
got pulled into other important things. Will get to it next week.

**Comment by andreabolognani** [comment]
> got pulled into other important things. Will get to it next week.

No problem, take your time. It's not urgent :)

**Pull request merged**
